# Generated by Django 6.1.1 on 2026-10-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesStatistic',
            fields=[
                ('statistic_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('statistic_date', models.DateField()),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_orders', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
