# Generated by Django 6.1.1 on 2026-10-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('view_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProductInteraction',
            fields=[
                ('interaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interacted_type', models.CharField(choices=[('VIEW', 'View'), ('CART', 'Cart'), ('PURCHASE', 'Purchase')], max_length=30)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
