# Generated by Django 6.1.1 on 2026-10-03 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentItemset',
            fields=[
                ('itemset_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('itemset_code', models.CharField(max_length=255)),
                ('support', models.DecimalField(decimal_places=6, max_digits=10)),
                ('item_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssociationRule',
            fields=[
                ('rule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('support', models.DecimalField(decimal_places=6, max_digits=10)),
                ('confidence', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lift', models.DecimalField(decimal_places=6, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('antecedent_itemset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedent_itemsets', to='recommendations.frequentitemset')),
                ('consequent_itemset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consequent_itemsets', to='recommendations.frequentitemset')),
            ],
        ),
        migrations.CreateModel(
            name='FrequentItemsetProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemset_products', to='recommendations.frequentitemset')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequent_itemsets', to='products.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('itemset', 'product'), name='unique_product_frequent_itemset')],
            },
        ),
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('recommendation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('similarity_score', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('recommendation_type', models.CharField(choices=[('SIMILAR_PRODUCT', 'Similar Product')], default='SIMILAR_PRODUCT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='products.product')),
                ('recommended_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_by', to='products.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'recommended_product'), name='unique_product_recommendation')],
            },
        ),
    ]
